---
- name: system patching
  hosts: centos7_64Guest
  tasks:
  - name: Yum to apply patches
    yum:
     name: '*'
     state: latest
     
  - name: apt to apply patches
    apt: apt: update_cache=yes force_apt_get=yes
     

